### ISSUE TITLE
unable to find libssl

### ISSUE THREAD

**Issue by botanize** [DingoBits/qgis-arm64-apple#3]
Hi, thanks for your work on this, I encountered this error while trying to load qgis-maptiler-plugin:

```
Couldn't load plugin 'qgis-maptiler-plugin' due to an error when calling its classFactory() method 

ImportError: dlopen(/Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_ssl.cpython-311-darwin.so, 0x0002): Library not loaded: @executable_path/../Frameworks/libssl.1.1.dylib   Referenced from: /Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_ssl.cpython-311-darwin.so   Reason: tried: '/Applications/QGIS.app/Contents/Frameworks/libssl.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libssl.1.1.dylib' (no such file), '/Applications/QGIS.app/Contents/Frameworks/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache) 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/__init__.py", line 35, in classFactory
    from .maptiler import MapTiler
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/maptiler.py", line 31, in 
    from .browser_root_collection import DataItemProvider
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_root_collection.py", line 7, in 
    from .browser_mapitem import MapDataItem
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 14, in 
    from .gl2qgis import converter
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/converter.py", line 19, in 
    from .gl2qgis import parse_layers, parse_background
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 23, in 
    from .. import utils
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reidjp/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/utils.py", line 7, in 
    import ssl
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 100, in 
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_ssl.cpython-311-darwin.so, 0x0002): Library not loaded: @executable_path/../Frameworks/libssl.1.1.dylib
  Referenced from:  /Applications/QGIS.app/Contents/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload/_ssl.cpython-311-darwin.so
  Reason: tried: '/Applications/QGIS.app/Contents/Frameworks/libssl.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libssl.1.1.dylib' (no such file), '/Applications/QGIS.app/Contents/Frameworks/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache)


Python version: 3.11.0 (main, Nov 13 2022, 14:13:08) [Clang 14.0.0 (clang-1400.0.29.202)] 
QGIS version: 3.28.1-Firenze Firenze, exported 
```

**Comment by eatyourbaby** [comment]
See #2.
